<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="coffeemachine" Id="{35bfe4e3-8924-4777-961e-1a20bedd5d86}" SpecialFunc="None">
    <Declaration><![CDATA[]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="coffeemachine">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>